import {
  Frame,
  FramesState,
  Sprite,
  isArrowSprite,
  isTextSprite,
} from "../Frames/reducers/frames";

// Renders the presentation as compact text for an LLM prompt.
//
// The raw FramesState cannot be sent as JSON: `frame.preview` holds a base64
// thumbnail, and `animationProps` / `reverseAnimationProps` hold derived motion
// data (a CHAOTIC sprite's is a 30-point coordinate array). All three are large,
// regenerated by the reducer anyway, and useless to a model deciding what to
// draw. This module projects only the authored, editable fields.
//
// Cost matters more here than in a normal prompt: the projection is re-rendered
// on every iteration of the tool loop, so its size is multiplied by the number
// of tool calls in a turn.

// Number of leading characters of a UUID used as its prompt handle. Ids are
// `crypto.randomUUID()` (36 chars) and appear once per sprite per turn, so the
// full value is the single most repetitive thing in the prompt. 8 hex chars is
// ~4 billion values — far beyond collision range for one presentation — and
// `resolveSpriteHandle` fails loudly rather than guessing if two ever collide.
const HANDLE_LENGTH = 8;

export const shortId = (id: number | string | null): string =>
  (id ?? "").toString().slice(0, HANDLE_LENGTH);

export type Resolution =
  | { ok: true; id: string | number }
  | { ok: false; reason: "not_found" }
  | { ok: false; reason: "ambiguous"; candidates: string[] };

const resolveAmong = (
  ids: Array<number | string>,
  handle: string,
): Resolution => {
  const needle = (handle ?? "").toString().trim();
  if (!needle) return { ok: false, reason: "not_found" };

  // Exact match wins outright, so a caller echoing a full id is never treated
  // as an ambiguous prefix.
  const exact = ids.find((id) => id.toString() === needle);
  if (exact !== undefined) return { ok: true, id: exact };

  const matches = Array.from(
    new Map(
      ids
        .filter((id) => id.toString().startsWith(needle))
        .map((id) => [id.toString(), id] as const),
    ).values(),
  );
  if (matches.length === 0) return { ok: false, reason: "not_found" };
  if (matches.length > 1) {
    return {
      ok: false,
      reason: "ambiguous",
      candidates: matches.map((id) => shortId(id)),
    };
  }
  return { ok: true, id: matches[0] };
};

// Resolves a handle emitted by the projection back to a real sprite id.
//
// Sprite ids are deliberately shared across frames — COPY_SPRITE_INTO_FRAME
// clones a sprite keeping its id, which is how computeNewFrames pairs sprites
// between adjacent frames to derive motion. So a handle is looked up across the
// whole presentation and duplicate occurrences of one id are not an ambiguity.
export const resolveSpriteHandle = (
  state: FramesState,
  handle: string,
): Resolution =>
  resolveAmong(
    state.frames.flatMap((f) => f.sprites.map((s) => s.id)),
    handle,
  );

export const resolveFrameHandle = (
  state: FramesState,
  handle: string,
): Resolution =>
  resolveAmong(
    state.frames.map((f) => f.id).filter((id): id is string | number => id != null),
    handle,
  );

// Defaults assigned by ADD_SPRITE. Fields still at their default are omitted
// from the projection — they carry no information and the model can assume them.
const DEFAULT_ANIMATION_TYPE = "LINEAR";
const DEFAULT_DURATION = 1;
const DEFAULT_OPACITY = 1;

const round = (n: number | undefined): number => Math.round(n ?? 0);

const truncate = (text: string, max: number): string =>
  text.length <= max ? text : `${text.slice(0, max - 1)}…`;

// Derives a human label for an image sprite from its storage path. Sprites do
// not persist their catalog name (only `backgroundUrl`), so the filename is the
// only description available — "sprites/Brain/Brain (healthy).svg" reads back as
// "Brain (healthy)". See the note in describeSprite's caller about storing the
// catalog name on future AI-added sprites.
const labelFromUrl = (url: string | undefined): string => {
  if (!url) return "untitled";
  const base = url.split("?")[0].split("/").pop() ?? "";
  const withoutExt = base.replace(/\.[a-z0-9]+$/i, "");
  return truncate(withoutExt.replace(/[-_]+/g, " ").trim() || "untitled", 60);
};

const describeSprite = (sprite: Sprite): string => {
  const parts: string[] = [shortId(sprite.id)];

  if (isTextSprite(sprite)) {
    parts.push("text", `"${truncate(sprite.text ?? "", 60)}"`);
  } else if (isArrowSprite(sprite)) {
    parts.push("arrow");
  } else {
    parts.push("image", `"${labelFromUrl(sprite.backgroundUrl)}"`);
  }

  parts.push(`@${round(sprite.position?.x)},${round(sprite.position?.y)}`);
  parts.push(`${round(sprite.width)}x${round(sprite.height)}`);

  if (round(sprite.rotation) !== 0) parts.push(`rot=${round(sprite.rotation)}`);
  if (sprite.opacity != null && sprite.opacity !== DEFAULT_OPACITY) {
    parts.push(`opacity=${sprite.opacity}`);
  }
  if (
    sprite.animationType &&
    sprite.animationType !== DEFAULT_ANIMATION_TYPE
  ) {
    parts.push(`anim=${sprite.animationType}`);
  }
  if (sprite.duration != null && sprite.duration !== DEFAULT_DURATION) {
    parts.push(`dur=${sprite.duration}`);
  }
  if (sprite.groupId) parts.push(`group=${shortId(sprite.groupId)}`);

  if (isTextSprite(sprite)) {
    if (sprite.fontSize) parts.push(`${sprite.fontSize}px`);
    if (sprite.fill) parts.push(sprite.fill);
  } else if (isArrowSprite(sprite) && sprite.stroke) {
    parts.push(sprite.stroke);
  }

  return parts.join(" ");
};

export interface ProjectionOptions {
  // Which frames are rendered sprite-by-sprite. Others collapse to a summary
  // line. Defaults to "neighbors": the current frame plus the one before and
  // after it, which is exactly the window computeNewFrames uses to derive
  // animation, so it is what the model needs to reason about motion.
  detail?: "current" | "neighbors" | "all";
  // Safety valve against a runaway frame flooding the context window.
  maxSpritesPerFrame?: number;
}

const summarizeFrame = (frame: Frame, index: number, total: number): string => {
  const count = frame.sprites?.length ?? 0;
  return `Frame ${index + 1}/${total} id=${shortId(frame.id)} "${frame.title}" (${count} sprite${count === 1 ? "" : "s"})`;
};

export function projectPresentation(
  state: FramesState,
  options: ProjectionOptions = {},
): string {
  const { detail = "neighbors", maxSpritesPerFrame = 80 } = options;
  const frames = state.frames ?? [];
  if (frames.length === 0) return "Presentation is empty (no frames).";

  const currentIndex = frames.findIndex(
    (f) => f.id?.toString() === state.currentFrame?.id?.toString(),
  );

  const isDetailed = (index: number): boolean => {
    if (detail === "all") return true;
    if (index === currentIndex) return true;
    return detail === "neighbors" && Math.abs(index - currentIndex) === 1;
  };

  const lines: string[] = [
    `Title: ${state.title || "(untitled)"}`,
    `${frames.length} frame${frames.length === 1 ? "" : "s"}`,
    "",
  ];

  frames.forEach((frame, index) => {
    if (!isDetailed(index)) {
      lines.push(summarizeFrame(frame, index, frames.length));
      return;
    }

    const header = [
      `Frame ${index + 1}/${frames.length}`,
      `id=${shortId(frame.id)}`,
      `"${frame.title}"`,
    ];
    if (index === currentIndex) header.push("(current)");
    if (frame.backgroundUrl) {
      header.push(`bg="${labelFromUrl(frame.backgroundUrl)}"`);
    }
    lines.push(header.join(" "));

    const sprites = frame.sprites ?? [];
    if (sprites.length === 0) {
      lines.push("  (empty)");
      return;
    }
    // Array order is z-order, back to front — SEND_SPRITES_TO_BACK and
    // BRING_SPRITES_TO_FRONT reorder this array rather than setting a z index.
    sprites.slice(0, maxSpritesPerFrame).forEach((sprite) => {
      lines.push(`  ${describeSprite(sprite)}`);
    });
    if (sprites.length > maxSpritesPerFrame) {
      lines.push(
        `  … ${sprites.length - maxSpritesPerFrame} more sprite(s) not shown`,
      );
    }
  });

  const selected = state.currentSprites ?? [];
  if (selected.length > 0) {
    lines.push("", `User selection: ${selected.map((s) => shortId(s.id)).join(", ")}`);
  }

  return lines.join("\n");
}

// Static explanation of the format above. Kept next to the renderer so the two
// cannot drift, but exported separately so the caller can put it in the cached
// system prompt while the projection itself goes in the per-turn user message —
// mixing them would invalidate the prompt cache on every turn.
export const PROJECTION_FORMAT_GUIDE = `Presentation state is given as text in this format:

Frame <n>/<total> id=<frameHandle> "<title>" [(current)] [bg="<name>"]
  <spriteHandle> <kind> "<label>" @<x>,<y> <width>x<height> [rot=<deg>] [opacity=<n>] [anim=<TYPE>] [dur=<s>] [group=<handle>] [extras]

- Handles are the first 8 characters of an id. Pass them back verbatim; never invent one.
- Sprites are listed back to front — later lines render on top of earlier ones.
- @x,y is the sprite's CENTRE, not its top-left corner.
- Omitted fields are at their defaults: rot=0, opacity=1, anim=LINEAR, dur=1.
- Frames outside the current one and its immediate neighbours are summarised to a single line. Switch the current frame to see a frame's contents in full.`;
