import React from "react";

export const rightDrawerWidth = 300;
export const bottomDrawerHeight = 240;
export const leftDrawerWidth = 300;

export const OFFSET = 200;
export const VIEWPORT_WIDTH = 810;
export const VIEWPORT_HEIGHT = 540;

export const SPRITES_BY_CATEGORY_TO_SVG_ELEMENT_MAP = {
  "Brain": {
    "Brain (degeneration)": {
      name: "Brain (degeneration)",
      tags: [
        "CNS",
        "alzheimer",
        "brain",
        "central nervous system",
        "degeneration",
        "disease",
        "neurodegeneration",
        "neuron loss",
        "neuroscience",
        "parkinson",
        "pathology",
      ],
    },
    "Brain (healthy)": {
      name: "Brain (healthy)",
      tags: [
        "CNS",
        "anatomy",
        "biology",
        "brain",
        "central nervous system",
        "healthy",
        "human",
        "neuron",
        "neuroscience",
        "organ",
      ],
    },
    "Neuron": {
      name: "Neuron",
      tags: [
        "CNS",
        "axon",
        "brain",
        "cell",
        "central nervous system",
        "cholinergic",
        "dementia",
        "healthy",
        "naked",
        "nerve cell",
        "neurobiology",
        "neuron",
        "synapse",
      ],
    },
    "Neuron (amyloid plaques)": {
      name: "Neuron (amyloid plaques)",
      tags: [
        "CNS",
        "alzheimer",
        "amyloid plaques",
        "beta amyloid",
        "brain",
        "dementia",
        "disease",
        "neurobiology",
        "neurodegeneration",
        "neuron",
        "pathology",
      ],
    },
    "Neuron (attacked)": {
      name: "Neuron (attacked)",
      tags: [
        "CNS",
        "cell damage",
        "central nervous system",
        "cytotoxicity",
        "immune attack",
        "inflammation",
        "nerve cell",
        "neurodegeneration",
        "neuroinflammation",
        "neuron",
        "pathology",
      ],
    },
    "Neuron (demyelination)": {
      name: "Neuron (demyelination)",
      tags: [
        "CNS",
        "axon",
        "central nervous system",
        "demyelination",
        "multiple sclerosis",
        "myelin loss",
        "nerve cell",
        "neurodegeneration",
        "neuroinflammation",
        "neuron",
        "pathology",
      ],
    },
  },
  "Cancer Cells": {
    "Cancer cell": {
      name: "Cancer cell",
      tags: [
        "biology",
        "cancer cell",
        "cell",
        "cell division",
        "disease",
        "malignant",
        "mutation",
        "oncology",
        "pathology",
        "tumor cell",
        "uncontrolled proliferation",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
  },
  "DNA and RNA": {
    "dsDNA (long)": {
      name: "dsDNA (long)",
      tags: [
        "DNA",
        "biology",
        "double helix",
        "gene",
        "genetic material",
        "genome",
        "long strand",
        "molecular biology",
        "nucleic acid",
        "nucleotide",
        "structure",
      ],
    },
    "dsDNA (short)": {
      name: "dsDNA (short)",
      tags: [
        "DNA",
        "biology",
        "double helix",
        "gene fragment",
        "genetic material",
        "molecular biology",
        "nucleic acid",
        "nucleotide",
        "short strand",
        "structure",
      ],
    },
    "RNA (long)": {
      name: "RNA (long)",
      tags: [
        "RNA",
        "gene expression",
        "long strand",
        "mRNA",
        "messenger RNA",
        "molecular biology",
        "nucleic acid",
        "nucleotide",
        "single stranded",
        "transcription",
      ],
    },
    "RNA (short)": {
      name: "RNA (short)",
      tags: [
        "RNA",
        "gene expression",
        "mRNA",
        "messenger RNA",
        "molecular biology",
        "nucleic acid",
        "nucleotide",
        "short strand",
        "single stranded",
        "transcription",
      ],
    },
  },
  "Immune Cells": {
    "B cell": {
      name: "B cell",
      tags: [
        "APC",
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody",
        "antigen presenting cell",
        "cell",
        "humoral",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "B cell (2D)": {
      name: "B cell (2D)",
      tags: [
        "2D",
        "APC",
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody",
        "antigen presenting cell",
        "cell",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Basophil": {
      name: "Basophil",
      tags: [
        "allergy",
        "basophil",
        "cell",
        "granulocyte",
        "histamine",
        "immune cell",
        "immunology",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Basophil (2D)": {
      name: "Basophil (2D)",
      tags: [
        "2D",
        "allergy",
        "basophil",
        "cell",
        "granulocyte",
        "histamine",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Dendritic cell": {
      name: "Dendritic cell",
      tags: [
        "APC",
        "T cell activation",
        "antigen presentation",
        "antigen presenting cell",
        "cell",
        "dendritic",
        "dendritic cell",
        "immune cell",
        "immunology",
        "innate",
        "innate immunity",
        "leukocyte",
        "surveillance",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Dendritic cell (2D)": {
      name: "Dendritic cell (2D)",
      tags: [
        "2D",
        "APC",
        "antigen presentation",
        "antigen presenting cell",
        "cell",
        "dendritic",
        "dendritic cell",
        "immune cell",
        "immunology",
        "innate",
        "innate immunity",
        "leukocyte",
        "schematic",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Dendritic cell (immature)": {
      name: "Dendritic cell (immature)",
      tags: [
        "APC",
        "antigen presenting cell",
        "antigen uptake",
        "cell",
        "dendritic",
        "dendritic cell",
        "immature",
        "immune cell",
        "immunology",
        "innate",
        "innate immunity",
        "leukocyte",
        "migration",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Dendritic cell (mature)": {
      name: "Dendritic cell (mature)",
      tags: [
        "APC",
        "T cell activation",
        "adaptive immunity",
        "antigen presentation",
        "antigen presenting cell",
        "cell",
        "dendritic",
        "dendritic cell",
        "immune cell",
        "immunology",
        "innate",
        "leukocyte",
        "mature",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Eosinophil": {
      name: "Eosinophil",
      tags: [
        "allergy",
        "cell",
        "eosinophil",
        "granulocyte",
        "immune cell",
        "immunology",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "parasite defense",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Eosinophil (2D)": {
      name: "Eosinophil (2D)",
      tags: [
        "2D",
        "allergy",
        "cell",
        "eosinophil",
        "granulocyte",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "parasite defense",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Follicular dendritic cell": {
      name: "Follicular dendritic cell",
      tags: [
        "APC",
        "antigen presentation",
        "cell",
        "follicular dendritic cell",
        "germinal center",
        "immune cell",
        "immunology",
        "innate",
        "leukocyte",
        "lymph node",
        "lymphoid",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Follicular dendritic cell (2D)": {
      name: "Follicular dendritic cell (2D)",
      tags: [
        "2D",
        "APC",
        "antigen presentation",
        "cell",
        "follicular dendritic cell",
        "germinal center",
        "immune cell",
        "immunology",
        "innate",
        "leukocyte",
        "lymphoid",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Macrophage": {
      name: "Macrophage",
      tags: [
        "APC",
        "antigen presentation",
        "antigen presenting cell",
        "cell",
        "defense",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "macrophage",
        "monocyte",
        "phagocyte",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Macrophage (2D)": {
      name: "Macrophage (2D)",
      tags: [
        "2D",
        "APC",
        "antigen presenting cell",
        "cell",
        "defense",
        "immune cell",
        "immunology",
        "innate",
        "innate immunity",
        "leukocyte",
        "macrophage",
        "phagocyte",
        "schematic",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Macrophage (phagocytosis)": {
      name: "Macrophage (phagocytosis)",
      tags: [
        "antigen presentation",
        "cell",
        "defense",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "macrophage",
        "monocyte",
        "phagocytosis",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Mast cell": {
      name: "Mast cell",
      tags: [
        "adaptive",
        "allergy",
        "cell",
        "degranulation",
        "granulocyte",
        "histamine",
        "immune cell",
        "immunology",
        "inflammation",
        "innate",
        "leukocyte",
        "mast cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Mast cell (2D)": {
      name: "Mast cell (2D)",
      tags: [
        "2D",
        "allergy",
        "cell",
        "granulocyte",
        "histamine",
        "immune cell",
        "inflammation",
        "innate",
        "leukocyte",
        "mast cell",
        "schematic",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Mast cell (degranulating)": {
      name: "Mast cell (degranulating)",
      tags: [
        "allergy",
        "cell",
        "degranulation",
        "granules",
        "histamine release",
        "immune cell",
        "immunology",
        "inflammation",
        "innate",
        "leukocyte",
        "mast cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Microglia": {
      name: "Microglia",
      tags: [
        "CNS",
        "brain",
        "cell",
        "central nervous system",
        "glia",
        "immune cell",
        "innate",
        "leukocyte",
        "macrophage",
        "microglia",
        "neuroinflammation",
        "phagocyte",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Microglia (2D)": {
      name: "Microglia (2D)",
      tags: [
        "2D",
        "CNS",
        "brain",
        "cell",
        "central nervous system",
        "glia",
        "immune cell",
        "innate",
        "leukocyte",
        "microglia",
        "neuroinflammation",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Microglia (immature)": {
      name: "Microglia (immature)",
      tags: [
        "CNS",
        "brain",
        "cell",
        "central nervous system",
        "glia",
        "immature",
        "immune cell",
        "innate",
        "leukocyte",
        "macrophage",
        "microglia",
        "neurodevelopment",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Monocyte": {
      name: "Monocyte",
      tags: [
        "blood",
        "cell",
        "immune cell",
        "immunology",
        "innate",
        "innate immunity",
        "leukocyte",
        "macrophage",
        "monocyte",
        "precursor",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Naive B cell": {
      name: "Naive B cell",
      tags: [
        "B cell",
        "adaptive",
        "adaptive immunity",
        "anergic",
        "antibody",
        "cell",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "naive",
        "naïve",
        "resting",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Naive T cell": {
      name: "Naive T cell",
      tags: [
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "naive",
        "naïve",
        "resting",
        "surveillance",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Naive T cell (2D)": {
      name: "Naive T cell (2D)",
      tags: [
        "2D",
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "naive",
        "naïve",
        "resting",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Natural killer cell": {
      name: "Natural killer cell",
      tags: [
        "NK cell",
        "antiviral",
        "cell",
        "cytotoxic",
        "defense",
        "immune cell",
        "immunology",
        "innate",
        "innate immunity",
        "leukocyte",
        "lymphocyte",
        "natural killer",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Natural killer cell (2D)": {
      name: "Natural killer cell (2D)",
      tags: [
        "2D",
        "NK cell",
        "cell",
        "cytotoxic",
        "immune cell",
        "immunology leukocyte",
        "innate",
        "innate immunity",
        "lymphocyte",
        "natural killer",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil": {
      name: "Neutrophil",
      tags: [
        "cell",
        "defense",
        "granulocyte",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "neutrophil",
        "phagocyte",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (2D)": {
      name: "Neutrophil (2D)",
      tags: [
        "2D",
        "cell",
        "defense",
        "granulocyte",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "neutrophil",
        "schematic",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (crawling)": {
      name: "Neutrophil (crawling)",
      tags: [
        "cell",
        "chemotaxis",
        "crawling",
        "granulocyte",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "motility",
        "neutrophil",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (diapedesis)": {
      name: "Neutrophil (diapedesis)",
      tags: [
        "cell",
        "diapedesis",
        "endothelium",
        "extravasation",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "neutrophil",
        "transmigration",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (migrating)": {
      name: "Neutrophil (migrating)",
      tags: [
        "cell",
        "chemotaxis",
        "granulocyte",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "migration",
        "motility",
        "neutrophil",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (NETosis)": {
      name: "Neutrophil (NETosis)",
      tags: [
        "NETosis",
        "cell",
        "cell death",
        "defense",
        "extracellular traps",
        "granulocyte",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "neutrophil",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (phagocytosing)": {
      name: "Neutrophil (phagocytosing)",
      tags: [
        "cell",
        "defense",
        "granulocyte",
        "immune cell",
        "inflammation",
        "innate",
        "innate immunity",
        "leukocyte",
        "neutrophil",
        "pathogen killing",
        "phagocytosis",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Plasma cell": {
      name: "Plasma cell",
      tags: [
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody",
        "cell",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "plasma cell",
        "secretion",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Plasma cell (2D)": {
      name: "Plasma cell (2D)",
      tags: [
        "2D",
        "B cell",
        "adaptive",
        "antibody",
        "cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "plasma cell",
        "schematic",
        "secretion",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Plasmablast": {
      name: "Plasmablast",
      tags: [
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody secretion",
        "cell",
        "differentiation",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "plasmablast",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell": {
      name: "T cell",
      tags: [
        "CD3",
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "defense",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell (2D)": {
      name: "T cell (2D)",
      tags: [
        "2D",
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "defense",
        "immune cell",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "schematic",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell (attacking)": {
      name: "T cell (attacking)",
      tags: [
        "CD8",
        "T cell",
        "adaptive",
        "adaptive immunity",
        "attacking",
        "cell",
        "cytotoxic",
        "immune response",
        "immunology",
        "killing",
        "leukocyte",
        "lymphocyte",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell (cytokine release)": {
      name: "T cell (cytokine release)",
      tags: [
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cancer",
        "cell",
        "cytokine",
        "immune response",
        "immunology",
        "inflammation",
        "leukocyte",
        "lymphocyte",
        "signaling",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell (migrating)": {
      name: "T cell (migrating)",
      tags: [
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "chemotaxis",
        "immune surveillance",
        "immunology",
        "leukocyte",
        "lymphocyte",
        "migrating",
        "migration",
        "motility",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
  },
  "Lab Animals": {
    "Fish": {
      name: "Fish",
      tags: [
        "animal",
        "biology",
        "development",
        "fish",
        "laboratory",
        "model",
        "model organism",
        "research",
        "vertebrate",
        "zebrafish",
      ],
    },
    "Mosquito": {
      name: "Mosquito",
      tags: [
        "animal",
        "blood",
        "disease",
        "entomology",
        "insect",
        "lab",
        "malaria",
        "mosquito",
        "parasite",
        "testing",
        "vector",
      ],
    },
    "Mosquito (superior)": {
      name: "Mosquito (superior)",
      tags: [
        "animal",
        "blood",
        "disease",
        "entomology",
        "insect",
        "lab",
        "malaria",
        "mosquito",
        "parasite",
        "testing",
        "vector",
      ],
    },
    "Mouse": {
      name: "Mouse",
      tags: [
        "animal",
        "genetics",
        "immunology",
        "lab",
        "labiology",
        "laboratory",
        "mammal",
        "model",
        "model organism",
        "mouse",
        "rat",
        "research",
      ],
      variants: ["black", "grey", "white"],
    },
  },
  "Lab Icons": {
    "Microscope": {
      name: "Microscope",
      tags: [
        "biology",
        "confocal",
        "imaging",
        "laboratory",
        "light",
        "microscope",
        "microscopy",
        "observation",
        "research",
        "science",
        "tool",
      ],
    },
    "Petri dish": {
      name: "Petri dish",
      tags: [
        "biology",
        "cells",
        "culture",
        "dish",
        "experiment",
        "lab tool",
        "microbiology",
        "petri dish",
        "research",
      ],
    },
    "Pipette": {
      name: "Pipette",
      tags: [
        "biology",
        "equipment",
        "experiment",
        "gilson",
        "lab",
        "laboratory",
        "liquid handling",
        "pipette",
        "research",
        "tool",
      ],
    },
  },
  "Molecules": {
    "B cell receptor (IgA, dimer)": {
      name: "B cell receptor (IgA, dimer)",
      tags: [
        "IgA",
        "Y shaped antibody",
        "adaptive immunity",
        "antibody",
        "antibody schematic",
        "antibody structure",
        "antigen binding",
        "dimer",
        "heavy chain light chain",
        "iga",
        "immune defense",
        "immunoglobulin A",
        "immunology",
        "mucosal immunity",
        "plasma cell",
        "secretory IgA",
      ],
    },
    "B cell receptor (IgA)": {
      name: "B cell receptor (IgA)",
      tags: [
        "B cell activation",
        "BCR",
        "IgA receptor",
        "adaptive immunity",
        "antigen recognition",
        "b cell receptor",
        "cell surface receptor",
        "immune response",
        "immunoglobulin A",
        "immunology",
        "membrane bound antibody",
        "mucosal immunity",
        "receptor schematic",
      ],
    },
    "B cell receptor (IgD)": {
      name: "B cell receptor (IgD)",
      tags: [],
    },
    "B cell receptor (IgE)": {
      name: "B cell receptor (IgE)",
      tags: [
        "B cell activation",
        "BCR",
        "IgE receptor",
        "adaptive immunity",
        "allergy",
        "antigen recognition",
        "b cell receptor",
        "cell surface receptor",
        "hypersensitivity",
        "immune response",
        "immunoglobulin E",
        "immunology",
        "membrane bound antibody",
        "receptor schematic",
      ],
      variants: ["green", "orange"],
    },
    "B cell receptor (IgG, flexible)": {
      name: "B cell receptor (IgG, flexible)",
      tags: [
        "B cell activation",
        "BCR",
        "IgG flexible",
        "adaptive immunity",
        "antibody flexibility",
        "antigen binding",
        "b cell receptor",
        "cell surface receptor",
        "conformational change",
        "hinge region",
        "immunology",
        "membrane bound antibody",
        "receptor schematic",
        "signaling",
      ],
    },
    "B cell receptor (IgG, upright)": {
      name: "B cell receptor (IgG, upright)",
      tags: [
        "B cell activation",
        "BCR",
        "IgG straight",
        "adaptive immunity",
        "antigen binding",
        "b cell receptor",
        "cell surface receptor",
        "immunology",
        "membrane bound antibody",
        "receptor schematic",
        "rigid conformation",
        "signaling",
        "structural conformation",
      ],
    },
    "B cell receptor (IgG)": {
      name: "B cell receptor (IgG)",
      tags: [
        "B cell activation",
        "BCR",
        "IgG receptor",
        "adaptive immunity",
        "antigen recognition",
        "b cell receptor",
        "cell surface receptor",
        "immune response",
        "immunoglobulin G",
        "immunology",
        "membrane bound antibody",
        "memory B cell",
        "receptor schematic",
        "signaling",
      ],
    },
    "B cell receptor (IgM, monomer)": {
      name: "B cell receptor (IgM, monomer)",
      tags: [
        "B cell activation",
        "BCR",
        "IgM receptor",
        "adaptive immunity",
        "antigen recognition",
        "b cell receptor",
        "cell surface receptor",
        "immune response",
        "immunology",
        "membrane bound antibody",
        "membrane immunoglobulin",
        "monomer",
        "naive B cell",
        "receptor schematic",
        "signaling",
      ],
    },
    "B cell receptor (IgM, pentamer 2)": {
      name: "B cell receptor (IgM, pentamer 2)",
      tags: [
        "IgM",
        "adaptive immunity",
        "antibody",
        "antibody schematic",
        "antibody structure",
        "antigen binding",
        "complement activation",
        "early immune response",
        "igm",
        "immunoglobulin M",
        "immunology",
        "multimeric antibody",
        "pentamer variant",
        "plasma cell",
        "primary response",
      ],
    },
    "B cell receptor (IgM, pentamer)": {
      name: "B cell receptor (IgM, pentamer)",
      tags: [
        "IgM",
        "adaptive immunity",
        "antibody",
        "antibody schematic",
        "antibody structure",
        "antigen binding",
        "complement activation",
        "early immunity",
        "igm",
        "immunoglobulin M",
        "immunology",
        "multimeric antibody",
        "pentamer",
        "plasma cell",
        "primary immune response",
      ],
    },
    "T cell receptor": {
      name: "T cell receptor",
      tags: [
        "T cell activation",
        "TCR",
        "adaptive immunity",
        "antigen recognition",
        "cell surface receptor",
        "immune synapse",
        "immunology",
        "lymphocyte",
        "peptide MHC",
        "receptor schematic",
        "simple groove",
        "simplified model",
        "t cell receptor",
      ],
      variants: ["purple"],
    },
    "TCR 2": {
      name: "TCR 2",
      tags: [],
    },
  },
  "Organs": {
    "Brain": {
      name: "Brain",
      tags: [
        "CNS",
        "anatomy",
        "brain",
        "healthy",
        "human",
        "nervous system",
        "neuron",
        "neuroscience",
        "organ",
      ],
    },
    "Heart": {
      name: "Heart",
      tags: [
        "cardiology",
        "cardiovascular",
        "circulation",
        "healthy anatomy",
        "heart",
        "human",
        "muscle",
        "organ",
      ],
    },
    "Human (outline)": {
      name: "Human (outline)",
      tags: [
        "anatomy",
        "biology",
        "body",
        "human",
        "human outline",
        "illustration",
        "man",
        "organ system",
        "outline",
        "schematic",
        "woman",
      ],
    },
    "Human arm": {
      name: "Human arm",
      tags: [
        "anatomy",
        "arm",
        "biology",
        "body",
        "human",
        "illustration",
        "limb",
        "skeletal muscle",
      ],
    },
    "Human leg": {
      name: "Human leg",
      tags: [
        "anatomy",
        "biology",
        "body",
        "foot",
        "human",
        "leg",
        "limb",
        "skeletal muscle",
      ],
    },
    "Intestine": {
      name: "Intestine",
      tags: [
        "GI tract",
        "absorption",
        "anatomy",
        "digestive system",
        "gut",
        "healthy",
        "human",
        "intestine",
        "large",
        "organ",
        "small",
      ],
    },
    "Kidney": {
      name: "Kidney",
      tags: [
        "anatomy",
        "filtration",
        "human",
        "kidney",
        "nephron",
        "organ",
        "renal",
        "urinary system",
      ],
    },
    "Liver": {
      name: "Liver",
      tags: [
        "anatomy",
        "biology",
        "detoxification",
        "healthy",
        "hepatocyte",
        "human",
        "liver",
        "metabolism",
        "organ",
      ],
    },
    "Lung": {
      name: "Lung",
      tags: [
        "alveoli",
        "anatomy",
        "biology",
        "gas exchange",
        "healthy",
        "human",
        "lung",
        "organ",
        "respiratory system",
      ],
    },
    "Lymph node": {
      name: "Lymph node",
      tags: [
        "B cell",
        "T cell",
        "anatomy",
        "immune organ",
        "immunology",
        "lymph node",
        "lymphatic system",
        "lymphocyte",
        "lymphoid",
        "organ",
      ],
    },
    "Lymph node (vascularised)": {
      name: "Lymph node (vascularised)",
      tags: [
        "anatomy",
        "blood",
        "drainage",
        "immune organ",
        "immunology",
        "lymph node",
        "lymphatic system",
        "lymphocyte",
        "lymphoid",
        "organ",
        "vascularised",
        "vessels",
      ],
    },
    "Spleen": {
      name: "Spleen",
      tags: [
        "anatomy",
        "blood filter",
        "immune organ",
        "immunology",
        "lymphocyte",
        "lymphoid",
        "organ",
        "red pulp",
        "spleen",
      ],
    },
  },
  "Structural Cells": {
    "Apoptotic cancer cell": {
      name: "Apoptotic cancer cell",
      tags: [
        "apoptosis",
        "apoptotic cell",
        "caspase",
        "cell",
        "cell death",
        "clearance",
        "debris",
        "dying cell",
        "immune response",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Apoptotic cancer cell (2D)": {
      name: "Apoptotic cancer cell (2D)",
      tags: [],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Apoptotic cell": {
      name: "Apoptotic cell",
      tags: [
        "apoptosis",
        "apoptotic cell",
        "caspase",
        "cell",
        "cell death",
        "debris",
        "dying cell",
        "immune clearance",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Apoptotic cell (2D)": {
      name: "Apoptotic cell (2D)",
      tags: [],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Collagen fibres": {
      name: "Collagen fibres",
      tags: [
        "ECM",
        "biology",
        "collagen",
        "connective tissue",
        "extracellular",
        "fiber",
        "matrix",
        "protein",
        "structure",
        "tissue",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Collagen fibres (2D)": {
      name: "Collagen fibres (2D)",
      tags: [
        "2D",
        "ECM",
        "biology",
        "collagen",
        "connective tissue",
        "extracellular",
        "matrix",
        "protein",
        "schematic",
        "structure",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Collagen fibres (dense, 2D)": {
      name: "Collagen fibres (dense, 2D)",
      tags: [
        "2D",
        "ECM",
        "biology",
        "collagen",
        "connective tissue",
        "dense",
        "extracellular",
        "matrix",
        "protein",
        "structure",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Collagen fibres (dense)": {
      name: "Collagen fibres (dense)",
      tags: [
        "ECM",
        "biology",
        "collagen",
        "connective tissue",
        "dense",
        "extracellular",
        "matrix",
        "protein",
        "structure",
        "tissue",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Endothelial cell": {
      name: "Endothelial cell",
      tags: [],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Endothelial cell (2D)": {
      name: "Endothelial cell (2D)",
      tags: [],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Endothelial cell 2": {
      name: "Endothelial cell 2",
      tags: [],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Endothelial cell 2 (2D)": {
      name: "Endothelial cell 2 (2D)",
      tags: [],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Epithelial cell": {
      name: "Epithelial cell",
      tags: [],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Epithelial cell (2D)": {
      name: "Epithelial cell (2D)",
      tags: [],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Fibroblast": {
      name: "Fibroblast",
      tags: [
        "ECM",
        "biology",
        "cell",
        "collagen",
        "connective tissue",
        "fibroblast",
        "matrix",
        "tissue",
        "wound healing",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Fibroblast (2D)": {
      name: "Fibroblast (2D)",
      tags: [
        "2D",
        "ECM",
        "biology",
        "cell",
        "connective tissue",
        "fibroblast",
        "matrix",
        "schematic",
        "tissue",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Fibroblast (activated, 2D)": {
      name: "Fibroblast (activated, 2D)",
      tags: [
        "2D",
        "ECM",
        "activated",
        "cell",
        "fibroblast",
        "matrix",
        "myofibroblast",
        "schematic",
        "tissue repair",
        "wound healing",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Fibroblast (activated)": {
      name: "Fibroblast (activated)",
      tags: [
        "ECM",
        "activated",
        "biology",
        "cell",
        "fibroblast",
        "fibrosis",
        "matrix",
        "myofibroblast",
        "tissue repair",
        "wound healing",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neuron": {
      name: "Neuron",
      tags: [
        "CNS",
        "axon",
        "brain",
        "cell",
        "central nervous system",
        "cholinergic",
        "dementia",
        "healthy",
        "naked",
        "nerve cell",
        "neurobiology",
        "neuron",
        "synapse",
      ],
    },
    "Neuron (2D)": {
      name: "Neuron (2D)",
      tags: [
        "2D",
        "CNS",
        "axon",
        "brain",
        "nerve cell",
        "neurobiology",
        "neuron",
        "schematic",
      ],
    },
    "Neuron (degrading, 2D)": {
      name: "Neuron (degrading, 2D)",
      tags: [
        "2D",
        "CNS",
        "alzheimer",
        "alzheimer's",
        "apoptosis",
        "axon",
        "brain",
        "central nervous system",
        "degrading",
        "dementia",
        "neurodegeneration",
        "neuron",
        "parkinson",
        "parkinson's",
      ],
    },
    "Neuron (degrading)": {
      name: "Neuron (degrading)",
      tags: [
        "CNS",
        "alzheimer",
        "alzheimer's",
        "apoptosis",
        "axon",
        "brain",
        "cholinergic",
        "degeneration",
        "degradation",
        "degrading",
        "dementia",
        "inflammation",
        "nerve cell",
        "neurodegeneration",
        "neuroinflammation",
        "neuron",
        "parkinson",
        "parkinson's",
      ],
    },
    "Neuron (sheathed, 2D)": {
      name: "Neuron (sheathed, 2D)",
      tags: [
        "2D",
        "CNS",
        "axon",
        "brain",
        "cell",
        "central nervous system",
        "cholinergic",
        "dementia",
        "glia",
        "healthy",
        "myelin sheath",
        "myelinated",
        "nerve",
        "nerve cell",
        "neurobiology",
        "neuron",
        "synapse",
      ],
    },
    "Neuron (sheathed)": {
      name: "Neuron (sheathed)",
      tags: [
        "CNS",
        "axon",
        "brain",
        "cell",
        "central nervous system",
        "cholinergic",
        "dementia",
        "glia",
        "healthy",
        "myelin sheath",
        "myelinated",
        "nerve",
        "nerve cell",
        "neurobiology",
        "neuron",
        "synapse",
      ],
    },
    "Platelets": {
      name: "Platelets",
      tags: [
        "blood",
        "cell",
        "cell fragment",
        "clotting",
        "coagulation",
        "hematology",
        "hemostasis",
        "platelet",
        "platelets",
        "thrombocyte",
        "thrombocytes",
      ],
      variants: ["grey", "yellow"],
    },
    "Platelets (2D)": {
      name: "Platelets (2D)",
      tags: [
        "2D",
        "blood",
        "cell fragment",
        "clotting",
        "coagulation",
        "hemostasis",
        "platelet",
        "platelets",
        "schematic",
        "thrombocyte",
        "thrombocytes",
      ],
      variants: ["grey", "yellow"],
    },
    "Red blood cell (bursting, 2D)": {
      name: "Red blood cell (bursting, 2D)",
      tags: [
        "2D",
        "blood",
        "cell",
        "erythrocyte",
        "hematology",
        "hemolysis",
        "infected",
        "infection",
        "lysis",
        "malaria",
        "red blood cell",
        "schematic",
      ],
    },
    "Red blood cell (bursting)": {
      name: "Red blood cell (bursting)",
      tags: [
        "blood",
        "bursting",
        "cell",
        "damage",
        "erythrocyte",
        "hematology",
        "hemolysis",
        "infected",
        "infection",
        "lysis",
        "malaria",
        "red blood cell",
      ],
    },
    "Red blood cell (lateral, 2D)": {
      name: "Red blood cell (lateral, 2D)",
      tags: [
        "2D",
        "biconcave",
        "blood",
        "cell",
        "erythrocyte",
        "hematology",
        "oxygen",
        "red blood cell",
        "schematic",
      ],
    },
    "Red blood cell (lateral)": {
      name: "Red blood cell (lateral)",
      tags: [
        "biconcave",
        "blood",
        "cell",
        "circulation",
        "erythrocyte",
        "hematology",
        "oxygen",
        "red blood cell",
        "transport",
      ],
    },
    "Red blood cell (superior, 2D)": {
      name: "Red blood cell (superior, 2D)",
      tags: [
        "2D",
        "blood",
        "cell",
        "erythrocyte",
        "hematology",
        "oxygen",
        "red blood cell",
        "schematic",
        "transport",
      ],
    },
    "Red blood cell (superior)": {
      name: "Red blood cell (superior)",
      tags: [
        "blood",
        "cell",
        "circulation",
        "erythrocyte",
        "hematology",
        "oxygen",
        "red blood cell",
        "top view",
        "transport",
      ],
    },
  },
} as const;

export const SPRITE_TO_SVG_ELEMENT_MAP: Record<
  string,
  { name: string; tags: string[]; category: string; variants?: string[] }
> = Object.fromEntries(
  Object.entries(SPRITES_BY_CATEGORY_TO_SVG_ELEMENT_MAP).flatMap(
    ([category, cells]) =>
      Object.entries(cells).map(([key, v]) => {
        const name = v.name || key;
        return [name, { ...v, category }];
      }),
  ),
);

// export const SPRITE_TO_SVG_ELEMENT_MAP = {
//   b_cell_1: { name: "B Cell 1", tags: ["Cell"], svg: <BCell1 id="b_cell_1" /> },
//   basophil: {
//     name: "Basophil",
//     tags: ["Cell"],
//     svg: <Basophil id="basophil" />,
//   },
//   dendritic_cell_1: {
//     name: "Dendritic Cell 1",
//     tags: [],
//     svg: <DendriticCell1 id="dendritic_cell_1" />,
//   },
//   dendritic_cell_2: {
//     name: "Dendritic Cell 2",
//     tags: [],
//     svg: <DendriticCell2 id="dendritic_cell_2" />,
//   },
//   t_cell_1: { name: "T Cell 1", tags: [], svg: <TCell1 id="t_cell_1" /> },
//   t_cell_2: { name: "T Cell 2", tags: [], svg: <TCell2 id="t_cell_2" /> },
//   fibroblast_1: {
//     name: "Fibroblast 1",
//     tags: [],
//     svg: <Fibroblast1 id="fibroblast_1" />,
//   },
//   macrophage_1: {
//     name: "Macrophage 1",
//     tags: [],
//     svg: <Macrophage1 id="macrophage_1" />,
//   },
//   mhc_class_i: {
//     name: "MHC Class I",
//     tags: [],
//     svg: <MhcClassI id="mhc_class_i" />,
//   },
//   mhc_class_ii: {
//     name: "MHC Class II",
//     tags: [],
//     svg: <MhcClassII id="mhc_class_ii" />,
//   },
//   monocyte: { name: "Monocyte", tags: [], svg: <Monocyte id="monocyte" /> },
//   natural_killer_cell_2: {
//     name: "Natural Killer Cell 2",
//     tags: [],
//     svg: <NaturalKillerCell2 id="natural_killer_cell_2" />,
//   },
//   natural_killer_cell: {
//     name: "Natural Killer Cell",
//     tags: [],
//     svg: <NaturalKillerCell id="natural_killer_cell" />,
//   },
//   neutrophil: {
//     name: "Neutrophil",
//     tags: [],
//     svg: <Neutrophil id="neutrophil" />,
//   },
//   TCR_1: { name: "TCR 1", tags: [], svg: <TCR1 id="TCR_1" /> },
//   TCR_2: { name: "TCR 2", tags: [], svg: <TCR2 id="TCR_2" /> },
//   BCR_IgA_Dimer: {
//     name: "BCR IgA Dimer",
//     tags: [],
//     svg: <BCRIgADimer id="BCR_IgA_Dimer" />,
//   },
//   BCR_IgA: { name: "BCR IgA", tags: [], svg: <BCRIgA id="BCR_IgA" /> },
//   BCR_IgD: { name: "BCR IgD", tags: [], svg: <BCRIgD id="BCR_IgD" /> },
//   BCR_IgE: { name: "BCR IgE", tags: [], svg: <BCRIgE id="BCR_IgE" /> },
//   BCR_IgE_2: { name: "BCR IgE 2", tags: [], svg: <BCRIgE2 id="BCR_IgE_2" /> },
//   BCR_IgG_flexible_1: {
//     name: "BCR IgG Flexible 1",
//     tags: [],
//     svg: <BCRIgGFlexible1 id="BCR_IgG_flexible_1" />,
//   },
//   BCR_IgG_flexible_2: {
//     name: "BCR IgG Flexible 2",
//     tags: [],
//     svg: <BCRIgGFlexible2 id="BCR_IgG_flexible_2" />,
//   },
//   BCR_IgG: { name: "BCR IgG", tags: [], svg: <BCRIgG id="BCR_IgG" /> },
//   BCR_IgM_monomer: {
//     name: "BCR IgM Monomer",
//     tags: [],
//     svg: <BCRIgMMonomer id="BCR_IgM_monomer" />,
//   },
//   BCR_IgM_pentamer: {
//     name: "BCR IgM Pentamer",
//     tags: [],
//     svg: <BCRIgMPentamer id="BCR_IgM_pentamer" />,
//   },
//   BCR_IgM_pentamer_2: {
//     name: "BCR IgM Pentamer 2",
//     tags: [],
//     svg: <BCRIgMPentamer2 id="BCR_IgM_pentamer_2" />,
//   },
//   upwork_cell_1: {
//     name: "Upwork Cell 1",
//     tags: [],
//     svg: <UpworkCell1 id="upwork_cells_1" />,
//   },
//   upwork_cell_3: {
//     name: "Upwork Cell 3",
//     tags: [],
//     svg: <UpworkCell3 id="upwork_cells_3" />,
//   },
//   upwork_cell_4: {
//     name: "Upwork Cell 4",
//     tags: [],
//     svg: <UpworkCell4 id="upwork_cells_4" />,
//   },
// } as const;
